<session>       ::= (<statement> <newline>)*

<statement>     ::= <expression> | <binding>

<binding>       ::= <NAME> <COLON> <expression>

<expression>    ::= <NAME>
               | <LPAR> <lambda> <NAME> <DOT> <expression> <RPAR>
               | <LPAR> <expression> <expression> <RPAR>

<lambda>        ::= <LAMBDA_CHR> | <BACKSLASH> | <LAMBDA_STR>

<DOT>           ::= '.'

<COLON>         ::= ':'

<LPAR>          ::= "("

<RPAR>          ::= ")"

<LAMBDA_CHR>    ::= "λ"

<LAMBDA_STR>    ::= "lambda"

<BACKSLASH>     ::= "\"

<NAME>          ::= [a-zA-Z0-9_]+
